### ISSUE TITLE
Steam big picture mode doesn't work

### ISSUE THREAD

**Issue by FreeFull** [Supreeeme/xwayland-satellite#18] opened 2024-05-21 10:51 UTC
When clicking the big picture button, the Steam window fails to go fullscreen, and also turns completely transparent (with only the border remaining). The only way to restore it to normal seems to be restarting Steam.

**Comment by Supreeeme** [comment] 2024-05-24 22:52
Do you see this consistently? I only see big picture occassionally fail to open (fixed with a restart of steam), and I don't see the transparent window.

**Comment by FreeFull** [comment] 2024-05-25 02:02
The behaviour does seem to be a bit different now: Big Picture will open up fullscreen, but with a black screen, but will eventually work after trying a few times

**Comment by Supreeeme** [comment] 2024-05-25 03:01
Ah yeah, this is more inline with what I'm seeing. I think this might be related to Xwayland 24.1, I don't have the black screen issues on 23...

**Comment by Minion3665** [comment] 2024-05-26 16:16
I'm reproducing this with NixOS+niri+xwayland 24, pinning xwayland to 23 solves the issue for me

**Comment by jonseppanen** [comment] 2024-05-27 15:10
Do you have a flake for your xwayland-satellite and pinned xwayland? Im having trouble getting this all to work with Niri myself...

**Comment by Minion3665** [comment] 2024-05-27 20:52
@jonseppanen
> Do you have a flake for your xwayland-satellite and pinned xwayland? Im having trouble getting this all to work with Niri myself...

yes, although I have seen issues with some of my games failing to launch when using pinned xwayland.

Regardless, here's my patch: https://git.clicks.codes/plugins/gitiles/Chimera/NixFiles/+/889835e018f7ad62cbd8e28854d5116085cb521d%5E%21/

You can't directly use the package from my flake, since as I haven't yet merged it. Probably I won't merge the xwayland 23 version anyway because of the game launch issues... Hopefully you'll find the package useful anyway. I'd particularly look at `packages/xwayland-satellite/default.nix` which is at the bottom of that diff.

If you'd like to ask any other questions about my package/that flake I imagine they'd be off-topic for the issue, please feel free to send me an email instead - `minion@clicks.codes`

**Comment by Supreeeme** [comment] 2024-05-29 03:11
Opened an issue for the black screen upstream: https://gitlab.freedesktop.org/xorg/xserver/-/issues/1679

**Comment by Supreeeme** [comment] 2024-06-04 22:50
There was an (Xwayland) patch posted in the upstream issue that fixed the black screen issue for me. As this is an upstream issue with a fix on the way, I'm gonna close this.

**Closed by Supreeeme** 2024-06-04 22:50 UTC

**Comment by Minion3665** [comment] 2024-08-18 21:40
I'm still getting this even with xwayland 24.1.2 - which contains the upstream patch ... may we look into reopening this?

**Comment by Supreeeme** [comment] 2024-08-20 03:08
I'm not able to reproduce this on 24.1.2 anymore - what distro?

**Comment by Minion3665** [comment] 2024-08-20 08:01
> I'm not able to reproduce this on 24.1.2 anymore - what distro?

I'm using nixos unstable (https://github.com/NixOS/nixpkgs/tree/c3aa7b8938b17aebd2deecf7be0636000d62a2b9), with niri-flake to configure niri (https://github.com/sodiboo/niri-flake/tree/e979c921c3d799672b333780d8582c0aeca7da85)
